Release PR 1.0.0
nf-core/hgtseq pull request #16
Opened 2022-10-13 14:32 UTC by carpanz

This is a PR to make the first release.

We have successfully tested the pipeline on eight 10 exomes datasets of different species (2 Human cohorts, Mouse, Macaca Mulatta, Macaca Fascicularis, Pan Paniscus, Bos Taurus and Canis Familiaris) and an additional larger dataset of 88 Human exomes. 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/hgtseq/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/hgtseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-10-13 16:13 UTC, lescai approved these changes
Massive work on testing the pipeline in dev.
Appreciate the effort put in documenting the usage, and also current limitations for this first release.
Unless there's minor things with coding style, which I would probably miss anyway, happy to approve!

2022-10-17 11:01 UTC, FriederikeHanssen commented on README.md
> +[![AWS CI](https://img.shields.io/badge/CI%20tests-full%20size-FF9900?labelColor=000000&logo=Amazon%20AWS)](https://nf-co.re/hgtseq/results)[![Cite with Zenodo](http://img.shields.io/badge/DOI-10.528
@apeltzer can zenodo already be turned on or only after the release?

2022-10-17 11:07 UTC, FriederikeHanssen commented on assets/analysis_report.Rmd
> +  genome = "hg38"
same here, just to be sure that this is right, also since above in the code there is mention of hg19

2022-10-17 12:31 UTC, jfy133 requested changes
Code looks fine to me in most cases, albeit some of the changes possibly making your lives more complicated in the future with template merges (mainly the scrapping of the input_check subworkflow)

However the documentation look rather problematic to me:

- Ouptut docs
  - Missing/broken markdown links
  - Seemingly out-of-order sections (qualimap/bamtools coming before preprocessing?)
  - I would like to see more fleshed out descriptions of what the actual files are/contain/what you would use them for (just listing example file names is not so useful IMO, nor is giving general descriptions of the tools without saying exactly what you are doing with them)

- The parameter docs are also rather slim, I would like long form `help` messages for each one, explaining more what each parameter does or how they should be formated. For example my questions when looking:

  - `taxonomy_id`: what is a `TaxID`? From GTDB? NCBI only? 
  - `multiqc_runkraken` Why do I (as a user) need to know whether there is Kraken data to add to MultiQC, shouldn't the pipeline do this for me?
  - `istest` Why is there another 'istest' paramater, shouldn't the `test` profile do this (although I do see you have 'hidden' this...)
  - `krakendb`: What is a compressed kraken database folder? Is `zip` or `bz2` ok? Or must it be in a specific format
  - `bwaindex`: path to what? All BWA files with a wildcard? Just the directory?
  - Why are you hiding a bunch of potentially useful preprocessing steps (such as `clip_r2`)

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/input_check.nf
> -// Check input samplesheet and get read channels
Reason why you're removing this entirely? Do you not want to do any input validation?

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/input_check.nf
> -// Check input samplesheet and get read channels
Reason why you're removing this entirely? Do you not want to do any input validation?

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/bam_qc/main.nf
> +    ch_versions = ch_versions.mix(SAMTOOLS_STATS.out.versions.first())
To simplify your main `hqtseq` code, you could do what you do with `versions` but with `multiqc` output files, e.g.

```
ch_multiqc = Channel.empty()
ch_multiqc = ch_multiqc.mix(SAMTOOLS_STATS.out.stats)
``` 

etc., then you can `emit` a single output channel with all hte logs, and only have to supply one a single input channel of your results to MultiQC (unlikely currently, where you have to mix each one separately at the full-workflow level)

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/classify_unmapped/main.nf
> +    ch_versions = ch_versions.mix(PARSEOUTPUTS.out.versions)
Is it correct only single output is parsed, and not `VIEW_BOTH`

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/classify_unmapped/main.nf
> +    ch_versions = ch_versions.mix(KRAKEN2_BOTH.out.versions)
Any reason why you are running this separately (assuming `both` corresponds to paired?), and not running with the autodetection functoinality the module already has?

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/classify_unmapped/main.nf
> +    ch_versions = ch_versions.mix(SAMTOOLS_VIEW_BOTH.out.versions)
What are the diferences between the two actually? I think I'm not following what the difference is betwen SINGLE/BOTH (might be good to document)

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/prepare_reads/main.nf
> +
```suggestion
// modules to include in this subworkflow
```

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/prepare_reads/main.nf
> +
```suggestion
```

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/prepare_reads/main.nf
> +        bwaindex      = params.fasta ? params.bwaindex      ? Channel.fromPath(params.bwaindex).collect()      : BWAMEM1_INDEX.out.index : []
Whoa tricky! But clever

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/reads_qc/main.nf
> +
```suggestion

include { FASTQC as FASTQC_UNTRIMMED } from '../../../modules/nf-core/fastqc/main'
include { FASTQC as FASTQC_TRIMMED   } from '../../../modules/nf-core/fastqc/main'

```

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/reads_qc/main.nf
> +
```suggestion
```

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/sortbam/main.nf
> +
```suggestion
```

2022-10-17 12:31 UTC, jfy133 commented on subworkflows/local/sortbam/main.nf
> +
```suggestion
```

2022-10-17 12:31 UTC, jfy133 commented on workflows/hgtseq.nf
> +        .map { create_input_channel(it) }
As above, is there a reason why you drop the checking and move this here (it'll make future template merges more complex, and with arguable dropping the samplesheet validation is also a degradation of quality)

2022-10-17 12:31 UTC, jfy133 commented on workflows/hgtseq.nf
> +    if (!params.isbam) {
I'm just wondering if this repeated checking against `isbam` with a whole separate parameter, couldn't you infer this from the ncol of the input sample, for example?

2022-10-17 12:31 UTC, jfy133 commented on workflows/hgtseq.nf
> +    }
This seems very highly specific, I guess if it's related to the conda issue we should again discuss why it's not working...

2022-10-17 12:31 UTC, jfy133 commented on workflows/hgtseq.nf
> +        [],
Are you sure you don't want to provide a config to specify the ordering of the MultiQC sections or logo a in the report?

2022-10-17 12:31 UTC, jfy133 commented on workflows/hgtseq.nf
> +
Again I feel this is polluting your main workflow script, and will make templtae merges more complex.

2022-10-17 14:47 UTC, carpanz commented on assets/analysis_report.Rmd
> +  genome = "hg38"
You're right. I forgot to take _seqinfo(hg19sub)_ off as we don't use it. Removed!

2022-10-19 08:11 UTC, apeltzer commented
@nf-core-bot fix linting

2022-10-19 08:27 UTC, carpanz commented on CITATIONS.md
> +- [Trim Galore](https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/)
Done!

2022-10-19 08:27 UTC, carpanz commented on README.md
> +<img src="docs/images/hgtseq_pipeline_metromap.png" alt="nf-core/circdna metromap" width="70%">
Done!

2022-10-19 08:32 UTC, carpanz commented on README.md
> -<!-- If you use  nf-core/hgtseq for your analysis, please cite it using the following doi: [10.5281/zenodo.XXXXXX](https://doi.org/10.5281/zenodo.XXXXXX) -->
Done!

2022-10-19 08:33 UTC, carpanz commented on assets/analysis_report.Rmd
> +author: "Simone Carpanzano and Francesco Lescai"
you're right, removed

2022-10-19 08:38 UTC, carpanz commented on conf/test_full.config
> +    kronadb  = 'https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/sarscov2/metagenome/krona_taxonomy.tab'
Done!

2022-10-19 12:39 UTC, carpanz commented on subworkflows/local/classify_unmapped/main.nf
> +    ch_versions = ch_versions.mix(PARSEOUTPUTS.out.versions)
ongoing discussion on slack

2022-10-19 12:39 UTC, carpanz commented on subworkflows/local/classify_unmapped/main.nf
> +    ch_versions = ch_versions.mix(SAMTOOLS_VIEW_BOTH.out.versions)
ongoing discussion on slack

2022-10-19 12:40 UTC, carpanz commented on subworkflows/local/classify_unmapped/main.nf
> +    ch_versions = ch_versions.mix(KRAKEN2_BOTH.out.versions)
ongoing discussion on slack

2022-10-20 10:42 UTC, carpanz commented
Thank you again for the super useful review!
As discussed offline on Slack, I have implemented the documentation with the missing requests.

Important suggestion for improvements, such as : 
- Missing function from template
- Tidyverse functions (bind_cols, bind_rows)
- Expanding input file extensions (.fq)

are noted and will be implemented in a minor release to be prepared soon.

2022-10-21 09:06 UTC, jfy133 reviewed
Output and input documentation is much improved. I think only thing missing now is a review of the parameters, for example in your test profiles you use `fasta` but the parameter documentation only shows `genome`...? Also you've added help info to the trimgalore trimming parameters but these are still hidden, as are useful things such as `bwaindex/bwamem2index` etc.

![image](https://user-images.githubusercontent.com/17950287/197158443-a27a5ebc-7b81-43a7-bdfb-d94d397c90d4.png)

2022-10-21 09:06 UTC, jfy133 commented on docs/usage.md
> +
Re my comment from the main readme: a shortend version of these two paras would be perfect as a pipeline description, as I finally understand exactly what you're trying to do ;).

Something like: 

```
hgtseq analyses host reference genome aligned reads to identify potential HGT integration sites, by comparing where each of the two reads in paired-reads map to, using metagenomic classification to find the potential source species of the integration.
```

(don't know if this is correct, but is sort of what I'm understanding now!)

2022-10-21 09:06 UTC, jfy133 commented on docs/usage.md
> +The FASTQ file extension can be either _fastq.gz_ or _fastq_.
For later release

2022-10-21 09:06 UTC, jfy133 commented on docs/usage.md
> +The user must specify the genome of interest. A list of genomes is available in the pipeline under the folder `conf/igenomes.config`, that contains illumina iGenomes reference file paths
Or is it `--fasta`? or do you support both?

2022-10-21 09:06 UTC, jfy133 commented on modules/local/ranalysis/main.nf
> +process RANALYSIS {
Maybe there you could try the nf-core Rnotebook module for a later relase

2022-10-21 12:17 UTC, lescai commented on conf/test.config
> +    gff             = 'https://raw.githubusercontent.com/nf-core/test-datasets/hgtseq/testdata/reference/Homo_sapiens.hg38.chr21.gff3'
Hi @jfy133 having been involved for quite a long time with Sarek here, we're managing the references mainly through the iGenomes config. 
this means the user is mainly exposed to the `--genome` param, which in turn sets all the other ones (fasta, gff, bwa etc). which is the beauty of using iGenome.
this - of course - does not prevent the user to look into the pipeline and choose to set those one by one. This - I believe - is well documented on nf-core where iGenomes is explained.

2022-10-21 12:18 UTC, lescai commented on docs/usage.md
> +The user must specify the genome of interest. A list of genomes is available in the pipeline under the folder `conf/igenomes.config`, that contains illumina iGenomes reference file paths
see above. 
I prefer the usage to be simplified and be handled through the iGenomes config.
in some of our tests where genomes are not in iGenomes, we've created a config following the nf-core iGenomes page, and still passed to our pipeline only the `--genome` param

2022-10-21 12:28 UTC, lescai commented
> Output and input documentation is much improved. I think only thing missing now is a review of the parameters, for example in your test profiles you use `fasta` but the parameter documentation only shows `genome`...? Also you've added help info to the trimgalore trimming parameters but these are still hidden, as are useful things such as `bwaindex/bwamem2index` etc.
> 
> ![image](https://user-images.githubusercontent.com/17950287/197158443-a27a5ebc-7b81-43a7-bdfb-d94d397c90d4.png)

Hi @jfy133 just to make sure I've replied to the correct comment, I'll probably repeat myself here.
Hiding parameters is a valid option, as often it happens you set the granularity to various levels. The params you mention are - in my view as it should be - hidden because they're set through the iGenomes config.
I like this solution nf-core has proposed, precisely because you set `fasta`, `gtf` `bwa` indexes and the likes just by setting the `--genome` parameter. In the spirit of flexibility though, it doesn't prevent the user to have more control, should they wish: but those params are neither required, nor cluttering the params page where `--genome` instead is required.
I'll be happy to have a more general conversation with others on how to improve this, but also in light of all the other pipelines already released, I'd probably be happy with the solution we've implemented :)

2022-10-21 13:20 UTC, carpanz commented on docs/usage.md
> +
done!

2022-10-21 13:22 UTC, carpanz commented on modules/local/ranalysis/main.nf
> +process RANALYSIS {
sure, we'll think about this.

2022-10-21 13:23 UTC, carpanz commented on README.md
> +**nf-core/hgtseq** is a bioinformatics best-practice analysis pipeline built to investigate horizontal gene transfer from NGS data.
done in PR #19 !

2022-10-21 13:23 UTC, carpanz commented on CITATIONS.md
> +  > Wood, Derrick E., Jennifer Lu, and Ben Langmead. 2019. Improved Metagenomic Analysis with Kraken 2. Genome Biology 20 (1): 257. doi: 10.1186/s13059-019-1891-0.
done!

2022-10-21 13:24 UTC, carpanz commented on docs/output.md
> +[`Parseoutputs`]() is our local module that allows us to parsing reads to get only the informations we need to perform analyzes in following R report.
fixed!

2022-10-24 06:08 UTC, lescai commented
Hi there,
thanks everyone and in particular @jfy133 @FriederikeHanssen for their contribution and minute review of this PR.
I'm taking the liberty to merge, because we do need the release to be linked in the manuscript we are about to submit, and this takes now priority.
I believe all suggestions have been discussed in here and on slack, and thoroughly addressed by @carpanz, particularly in the documentation, which I hope can now serve as example to the work of others in nf-core.
Any outstanding suggestions has been listed and agreed for prioritisation in the next release.
I'm very grateful for the team work and the fruitful exchange during this process.

2022-10-24 06:08 UTC, merged

2022-10-24 06:29 UTC, jfy133 commented
Spoken in slack (unfortunately before the merge): I will do one last check before we do the actual release

2022-10-24 07:36 UTC, jfy133 reviewed
Last few things:

- README introduction: the pipeline brackground is still maybe a bit too detailed, now it's not friday - what about:

    ```
    nf-core/hgtseq is a bioinformatics best-practice analysis pipeline built to investigate horizontal 
    gene transfer from NGS data. 

    The pipeline uses metagenomic classification of paired-read alignments against a reference 
    genome to identify discrepencies in species assignment between within read pairs to identify 
    potential integration sites into the host genome.  
    ```
    
    This will also make the pipeline summary abit clearer I think.
    
- README: The metromap doesn't fully work in darkmode (but not important)

![image](https://user-images.githubusercontent.com/17950287/197467778-8a067785-de6c-422f-8554-4c105fbaa3a0.png)

- USAGE: Does the pipeline work with single-end reads? My understanding is that it requires pairs , in which case the first line of `Input Formats` is in correct.
- USAGE/Nextflow_schema: make sure you mentio nin both places the krona/kraken2 databases can be tar.gz'd (currently only in parameters)
- We have broken markdown links under 'pipeline arguments' https://nf-co.re/hgtseq/dev/usage#pipeline-arguments, likely due to the backticks, I would remove this formatting.
- citations.md: missing - [bamtools (gh repo only)](https://github.com/pezmaster31/bamtools), [bwamem2](https://github.com/bwa-mem2/bwa-mem2#citation)
- JSON schema: given you have a fix listed of aligners, you should make this with an `enum` (press the cog next to the parameter when in the schema build), I think you also say you support `aln`, so that should be added?

Otherwise once these are in I can give you a retroactive ✅ and we can complete the rest of the release @carpanz @lescai

2022-10-24 12:38 UTC, jfy133 commented
OK, my final requests have been merged in with #23 #24  etc.! So imagine a ✅