Release 1.1.0
nf-core/hgtseq pull request #33
Opened 2023-05-12 14:00 UTC by carpanz

In this PR we include:

- Template and nf-core/modules update to the latest version
- Addition of Krona and Circos plot as example to documentation
- Addition of local module samtools/viewsingle. When extracting reads, we noticed that also some _both_unmapped_ reads were collected in _single_unmapped_ reads due to a conflict between flags option. In order to resolve this issue, we create a local module where we execute the extraction in two step (i.e. we combine two command with a pipe) instead of running the module twice, which would otherwise be inefficient.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/hgtseq/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/hgtseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-05-12 15:06 UTC, lescai approved these changes
Reviewed in dev already. 
Code looks good to me, all checks are passed.
Important to release the bug fix. This is also a chance to sync the pipeline to latest version of modules and software as well as to strengthen documentation.

2023-05-13 06:44 UTC, FriederikeHanssen requested changes
Almost there 🚀

2023-05-13 06:44 UTC, FriederikeHanssen commented on modules/local/samtools/viewsingle/main.nf
> +        'https://depot.galaxyproject.org/singularity/samtools:1.15.1--h1170115_0' :
Sam tools version not updated. Looks like you too this module from nf-core and modified it. You could also install the module as normal and then apply "patch". That way version changes are automatically installed

2023-05-13 06:44 UTC, FriederikeHanssen commented on nextflow.config
> +    version = '1.1.0'
The indent is off

2023-05-15 11:01 UTC, carpanz commented on nextflow.config
> +    version = '1.1.0'
done!

2023-05-15 11:02 UTC, carpanz commented on modules/local/samtools/viewsingle/main.nf
> +        'https://depot.galaxyproject.org/singularity/samtools:1.15.1--h1170115_0' :
Resolved! Discussed offline on Slack.

2023-05-15 17:13 UTC, FriederikeHanssen approved these changes
🚀  great work

2023-05-16 07:31 UTC, merged